tap "jandedobbeleer/oh-my-posh"
# GNU compiler collection
brew "gcc"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Platform built on V8 to build network applications
brew "node"
# Fast, disk space efficient package manager
brew "pnpm"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Safe, concurrent, practical language
brew "rust"
# UNIX shell (command interpreter)
brew "zsh"
cask "font-fira-code-nerd-font"
cask "font-noto-color-emoji"
